# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the deploy branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  repository_dispatch:
    types: [update]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Checkout theme repo
        uses: actions/checkout@v4
        with:
          repository: PaiJi/blog
          ref: main
          path: src/content/blog
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/iron"
          cache: yarn
      - name: Install dependencies
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: Save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          # Artifact name
          name: dist
          # Destination path
          path: dist/

      - name: Set private key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          # Private SSH key to register in the SSH agent
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Scan public keys
        run: |
          ssh-keyscan www.jipai.moe >> ~/.ssh/known_hosts

      - name: Rsync file
        run: |
          rsync -avz --delete dist/ deploy@www.jipai.moe:/home/deploy/web/blog.jipai.moe/
